version: '3'
services:
    web:
        build: 
          context: .
          dockerfile: Dockerfile
        command: yarn start
        ports:
            - 3000:3000
        deploy:
          replicas: 1
          resources:
            limits:
              cpus: 0.50
              memory: 1G
            reservations:
              cpus: 0.25
              memory: 512M
          restart_policy:
            condition: on-failure
        environment: 
            REACT_APP_API_URL: https://emmanuel-json-webserver.herokuapp.com
            REACT_APP_PAGE_SIZE: 16
            PORT: 3000
        volumes:
            - ./:/app

volumes:
    app:
