# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  gcp-cli: circleci/gcp-cli@2.2.0
  gke: circleci/gcp-gke@1.1.0
  docker: circleci/docker@1.4.0

jobs: # A basic unit of work in a run
  dockerize:
    executor: docker/docker
    steps:
      - run:
          name: Set Environment
          command: |
            echo 'export DOCKER_IMAGE=getir' >> $BASH_ENV
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD

      - docker/build:
          extra_build_args: '--build-arg REACT_APP_API_URL=${REACT_APP_API_URL} --build-arg REACT_APP_PAGE_SIZE=${REACT_APP_PAGE_SIZE}'
          image: '${DOCKER_LOGIN}/${DOCKER_IMAGE}'
          tag: '0.1.${CIRCLE_SHA1}'
      
      - docker/push:
          image: '${DOCKER_LOGIN}/${DOCKER_IMAGE}'
          tag: '0.1.${CIRCLE_SHA1}'

  build:
    docker:
      - image: cimg/node:16.6.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test
      
      # - run:
      #     name: Build app
      #     command: npm run build
  
  deploy_k8:
    machine: true
    steps:
      - run:
          name: Set Environment
          command: echo 'export DOCKER_IMAGE=getir' >> $BASH_ENV
          
      - gke/install
      - gke/update-kubeconfig-with-credentials:
          cluster: ${GCLOUD_CLUSTER}
          perform-login: true
      # - run:
      #     name: Create DOcker secret
      #     command: |
      #       kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=${DOCKER_LOGIN} --docker-password=${DOCKER_PASSWORD} --docker-email=${DOCKER_EMAIL}

      - gke/rollout-image:
          cluster: ${GCLOUD_CLUSTER}
          deployment: web
          container: getir
          image: '${DOCKER_LOGIN}/${DOCKER_IMAGE}'
          tag: '0.1.${CIRCLE_SHA1}'

  deploy_on_app_engine:
    machine: true
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize

      - run:
          name: Copy across app.yaml config
          command: ./app.yaml.sh > ./app.yaml

      - run:
          name: Deploy to App Engine
          command: google cloud deploy app.yaml

            

workflows: # A sequence of build steps using an executor or docker image
  deploy: # This is the name of the workflow, 
    jobs: # A basic unit of work in a run
      - build

      - dockerize:
          requires:
            - build
          filters: 
            branches:
              only:
                - main
      
      - deploy_k8:
          name: deploy-k8-on-staging
          requires:
            - dockerize
          filters:
            branches:
              only:
                - main
      
      - approve_prod_deployment:
          type: approval
          requires:
            - deploy-k8-on-staging
            - deploy-app-engine-on-staging

      - deploy_k8:
          name: deploy-prod
          context: production
          requires:
            - approve_prod_deployment

      - deploy_on_app_engine:
          name: deploy-app-engine-on-staging
          requires:
            - build
          filters:
            branches:
              only:
                - main

