# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  gcp-cli: circleci/gcp-cli@2.2.0
  gke: circleci/gcp-gke@1.1.0
  docker: circleci/docker@1.7.0

jobs: # A basic unit of work in a run
  build:
    docker:
      - image: cimg/node:16.6.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      
      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
  
  deploy_k8:
    machine: true
    steps:
      - run:
          name: Set Environment
          command: echo 'export DOCKER_IMAGE=temmyogunbo/getir' >> $BASH_ENV
          
      - gke/install
      - gke/update-kubeconfig-with-credentials:
          cluster: ${GCLOUD_CLUSTER}
      - gke/rollout-image:
          cluster: ${GCLOUD_CLUSTER}
          deployment: web
          container: getir
          image: ${DOCKER_IMAGE}
          tag: ${CIRCLE_SHA1}
#   # deploy_App_Engine:

workflows: # A sequence of build steps using an executor or docker image
  build: # This is the name of the workflow, 
    jobs: # A basic unit of work in a run
      - build

      - docker/publish:
          executor:
            image: circleci/node
            name: docker/docker
            tag: boron-browsers
          extra_build_args: '--build-arg REACT_APP_API_URL=${REACT_APP_API_URL} --build-arg REACT_APP_PAGE_SIZE=${REACT_APP_PAGE_SIZE}'
          image: getir
          tag: '0.1.${CIRCLE_SHA1}'
          use-docker-credentials-store: false
          requires:
            - build
          filters: 
            branches:
              only:
                - main

      - deploy_k8:
          requires:
            - docker/publish
          filters:
            branches:
              only:
                - main
