apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - image: temmyogunbo/getir:3.0
        name: getir
        command: ["/bin/sh", "-c"]
        args: 
          # - yarn add -D npm:@tailwindcss/postcss7-compat
          - yarn start
        env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: env-file
                key: REACT_APP_API_URL

          - name: REACT_APP_PAGE_SIZE
            valueFrom:
              configMapKeyRef:
                name: env-file
                key: REACT_APP_PAGE_SIZE
        readinessProbe:
          httpGet:
            path: /status
            port: 3000
          periodSeconds: 15
        
        # livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          
        volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
          
        ports:
          - containerPort: 3000
            protocol: TCP
        resources:
          limits: 
            cpu: 500m
            memory: 2Gi
              # You must specify requests for CPU to autoscale
              # based on CPU utilization
          requests:
            cpu: 500m
            memory: 2Gi
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: env-file
