  apiVersion: v1
  kind: Service
  metadata:
    name: web-service
  spec:
    type: LoadBalancer
    # sessionAffinity: ClientIP
    selector:
      app: web
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000